### ISSUE TITLE
Title not reset, if subsequent message does not set a new one.

### ISSUE THREAD

**Issue by vsviridov** [PaquitoSoft/Notimoo#1]
Example

```
notimoo.send({'title':'test', 'message':'message'});
notimoo.send({'message':'message2'});
```

message2 will contain title "test".

**Comment by PaquitoSoft** [comment]
Thanks for reporting this issue. I'll solve it as soon as I have some time available.

**Comment by PaquitoSoft** [comment]
Today I had time to test this issue and is not true what it says.
First, Notimoo does not have a send() function, and calling show() function the way the issue states it works successfully.

**Comment by vsviridov** [comment]
http://jsfiddle.net/wQyZJ/1/

See for yourself.

**Comment by PaquitoSoft** [comment]
Ok, thanks for updating your test. Now I know what is happening
